# Generated by Django 3.2.18 on 2023-05-17 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
