# Generated by Django 3.2.18 on 2023-05-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='message',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
