# Generated by Django 3.2.18 on 2023-05-21 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20230519_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='message',
            new_name='text',
        ),
    ]
