# Generated by Django 3.2.18 on 2023-05-21 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_message_testimonial_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='text',
            new_name='message',
        ),
    ]
