# Generated by Django 3.2.18 on 2023-05-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_text_testimonial_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='facebook',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
