# Generated by Django 3.2.18 on 2023-05-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_staff_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='instagram',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='linkedin',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
