# Generated by Django 3.2.18 on 2023-06-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_customer_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='items',
        ),
        migrations.AddField(
            model_name='customer',
            name='items',
            field=models.ManyToManyField(blank=True, to='home.Items'),
        ),
    ]
