# Generated by Django 3.2.18 on 2023-06-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20230613_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pre_order',
            field=models.ManyToManyField(blank=True, to='home.Items'),
        ),
    ]
