# Generated by Django 3.2.18 on 2023-06-19 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
