# Generated by Django 3.2.18 on 2023-06-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20230619_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='digital',
            field=models.BooleanField(default=False),
        ),
    ]
