# Generated by Django 4.2.7 on 2023-12-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('0 TO 100', '100-150'), ('150 TO 200', '200 TO 250')], max_length=60)),
            ],
        ),
    ]
