# Generated by Django 4.2.7 on 2023-12-12 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_orderitem_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filter_Price',
        ),
    ]
