# Generated by Django 4.2.7 on 2023-12-14 07:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0040_alter_rating_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='ReviewRating',
        ),
    ]
